name: Rust

on:
  push:
    branches: [ master ]

jobs:
  overlay:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build overlay
      run: make
      working-directory: TrainingModpackOverlay
    - name: Upload overlay artifact
      uses: actions/upload-artifact@v2
      with:
        name: overlay
        path: TrainingModpackOverlay/ovlTrainingModpack.ovl
  plugin:
    runs-on: ubuntu-latest
    container: jugeeya/cargo-skyline:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Link rust-std-skyline src
      run: mkdir ../rust-std-skyline-squashed && ln -s $XARGO_RUST_SRC ../rust-std-skyline-squashed/src
    - name: Build release NRO
      run: cargo skyline build --release
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: target/aarch64-skyline-switch/release/libtraining_modpack.nro
  upload:
    runs-on: ubuntu-latest
    needs:
      - overlay
      - plugin
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Prepare zip
      env:
        SMASH_PLUGIN_DIR: atmosphere/contents/01006A800016E000/romfs/skyline/plugins
        TESLA_OVERLAY_DIR: switch/.overlays
      run: | 
        mkdir -p ${{env.SMASH_PLUGIN_DIR}} 
        cp plugin/libtraining_modpack.nro ${{env.SMASH_PLUGIN_DIR}}/libtraining_modpack.nro
        wget https://github.com/ultimate-research/params-hook-plugin/releases/download/v0.1/libparam_hook.nro
        cp libparam_hook.nro ${{env.SMASH_PLUGIN_DIR}}/libparam_hook.nro
        mkdir -p ${{env.TESLA_OVERLAY_DIR}}
        cp overlay/ovlTrainingModpack.ovl ${{env.TESLA_OVERLAY_DIR}}/ovlTrainingModpack.ovl
        zip -r training_modpack_beta.zip atmosphere switch
    - name: Update Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: beta
        name: beta
        body: >
          Beta built off of the latest code in the repository. 
          
          Use the files on the ZIP to replace your existing files from a full Release zip.
          
          - `atmosphere/contents/01006A800016E000/romfs/skyline/plugins/libtraining_modpack.nro` is the mod for the game itself
          - `switch/.overlays/ovlTrainingModpack.ovl` is the Tesla submenu
        files: >
          training_modpack_beta.zip
    - name: Upload zip as artifact
      uses: actions/upload-artifact@v1
      with:
        name: full_build
        path: training_modpack_beta.zip
